# Form implementation generated from reading ui file '/Users/benjicosby/Desktop/improveBudgetApp/displayWindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_displayWindow(object):
    def setupUi(self, displayWindow):
        displayWindow.setObjectName("displayWindow")
        displayWindow.resize(680, 618)
        displayWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0.311828 rgba(118, 255, 163, 252), stop:0.688172 rgba(65, 183, 60, 255));")
        self.centralwidget = QtWidgets.QWidget(parent=displayWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.primaryLbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.primaryLbl.setGeometry(QtCore.QRect(120, 90, 221, 61))
        self.primaryLbl.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.primaryLbl.setStyleSheet("background-color: rgb(118,255,163) ;\n"
"font-size: 24px;\n"
"font: italic bold;\n"
"color: rgb(65,183,60);\n"
"padding-left: 15px;\n"
"padding-right: 15px;\n"
"border-radius: 25px")
        self.primaryLbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.primaryLbl.setObjectName("primaryLbl")
        self.sideLbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.sideLbl.setGeometry(QtCore.QRect(120, 160, 221, 61))
        self.sideLbl.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.sideLbl.setStyleSheet("background-color: rgb(118,255,163) ;\n"
"font-size: 24px;\n"
"font: italic bold;\n"
"color: rgb(65,183,60);\n"
"padding-left: 15px;\n"
"padding-right: 15px;\n"
"border-radius: 25px")
        self.sideLbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sideLbl.setObjectName("sideLbl")
        self.totalLbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.totalLbl.setGeometry(QtCore.QRect(120, 230, 221, 61))
        self.totalLbl.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.totalLbl.setStyleSheet("background-color: rgb(118,255,163) ;\n"
"font-size: 24px;\n"
"font: italic bold;\n"
"color: rgb(65,183,60);\n"
"padding-left: 15px;\n"
"padding-right: 15px;\n"
"border-radius: 25px")
        self.totalLbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.totalLbl.setObjectName("totalLbl")
        self.needsLbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.needsLbl.setGeometry(QtCore.QRect(120, 300, 221, 61))
        self.needsLbl.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.needsLbl.setStyleSheet("background-color: rgb(118,255,163) ;\n"
"font-size: 24px;\n"
"font: italic bold;\n"
"color: rgb(65,183,60);\n"
"padding-left: 15px;\n"
"padding-right: 15px;\n"
"border-radius: 25px")
        self.needsLbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.needsLbl.setObjectName("needsLbl")
        self.wantsLbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.wantsLbl.setGeometry(QtCore.QRect(120, 370, 221, 61))
        self.wantsLbl.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.wantsLbl.setStyleSheet("background-color: rgb(118,255,163) ;\n"
"font-size: 24px;\n"
"font: italic bold;\n"
"color: rgb(65,183,60) ;\n"
"padding-left: 15px;\n"
"padding-right: 15px;\n"
"border-radius: 25px")
        self.wantsLbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.wantsLbl.setObjectName("wantsLbl")
        self.saveLbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.saveLbl.setGeometry(QtCore.QRect(120, 440, 221, 61))
        self.saveLbl.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.saveLbl.setStyleSheet("background-color: rgb(118,255,163) ;\n"
"font-size: 24px;\n"
"font: italic bold;\n"
"color: rgb(65,183,60);\n"
"padding-left: 15px;\n"
"padding-right: 15px;\n"
"border-radius: 25px")
        self.saveLbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.saveLbl.setObjectName("saveLbl")
        self.primaryDisplay = QtWidgets.QLabel(parent=self.centralwidget)
        self.primaryDisplay.setGeometry(QtCore.QRect(360, 90, 221, 61))
        self.primaryDisplay.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.primaryDisplay.setStyleSheet("background-color: rgb(118,255,163) ;\n"
"font-size: 24px;\n"
"font: italic bold;\n"
"color: rgb(65,183,60);\n"
"padding-left: 15px;\n"
"padding-right: 15px;\n"
"border-radius: 25px")
        self.primaryDisplay.setText("")
        self.primaryDisplay.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.primaryDisplay.setObjectName("primaryDisplay")
        self.sideDisplay = QtWidgets.QLabel(parent=self.centralwidget)
        self.sideDisplay.setGeometry(QtCore.QRect(360, 160, 221, 61))
        self.sideDisplay.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.sideDisplay.setStyleSheet("background-color: rgb(118,255,163) ;\n"
"font-size: 24px;\n"
"font: italic bold;\n"
"color: rgb(65,183,60);\n"
"padding-left: 15px;\n"
"padding-right: 15px;\n"
"border-radius: 25px")
        self.sideDisplay.setText("")
        self.sideDisplay.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sideDisplay.setObjectName("sideDisplay")
        self.totalDisplay = QtWidgets.QLabel(parent=self.centralwidget)
        self.totalDisplay.setGeometry(QtCore.QRect(360, 230, 221, 61))
        self.totalDisplay.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.totalDisplay.setStyleSheet("background-color: rgb(118,255,163) ;\n"
"font-size: 24px;\n"
"font: italic bold;\n"
"color: rgb(65,183,60);\n"
"padding-left: 15px;\n"
"padding-right: 15px;\n"
"border-radius: 25px")
        self.totalDisplay.setText("")
        self.totalDisplay.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.totalDisplay.setObjectName("totalDisplay")
        self.needsDisplay = QtWidgets.QLabel(parent=self.centralwidget)
        self.needsDisplay.setGeometry(QtCore.QRect(360, 300, 221, 61))
        self.needsDisplay.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.needsDisplay.setStyleSheet("background-color: rgb(118,255,163) ;\n"
"font-size: 24px;\n"
"font: italic bold;\n"
"color: rgb(65,183,60);\n"
"padding-left: 15px;\n"
"padding-right: 15px;\n"
"border-radius: 25px")
        self.needsDisplay.setText("")
        self.needsDisplay.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.needsDisplay.setObjectName("needsDisplay")
        self.wantsDisplay = QtWidgets.QLabel(parent=self.centralwidget)
        self.wantsDisplay.setGeometry(QtCore.QRect(360, 370, 221, 61))
        self.wantsDisplay.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.wantsDisplay.setStyleSheet("background-color: rgb(118,255,163) ;\n"
"font-size: 24px;\n"
"font: italic bold;\n"
"color: rgb(65,183,60);\n"
"padding-left: 15px;\n"
"padding-right: 15px;\n"
"border-radius: 25px")
        self.wantsDisplay.setText("")
        self.wantsDisplay.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.wantsDisplay.setObjectName("wantsDisplay")
        self.saveDisplay = QtWidgets.QLabel(parent=self.centralwidget)
        self.saveDisplay.setGeometry(QtCore.QRect(360, 440, 221, 61))
        self.saveDisplay.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.saveDisplay.setStyleSheet("background-color: rgb(118,255,163) ;\n"
"font-size: 24px;\n"
"font: italic bold;\n"
"color: rgb(65,183,60);\n"
"padding-left: 15px;\n"
"padding-right: 15px;\n"
"border-radius: 25px")
        self.saveDisplay.setText("")
        self.saveDisplay.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.saveDisplay.setObjectName("saveDisplay")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(510, 0, 171, 16))
        self.label.setStyleSheet("background-color: none;\n"
"color: rgb(255,255,255);\n"
"")
        self.label.setObjectName("label")
        self.titleLbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.titleLbl.setGeometry(QtCore.QRect(170, 20, 341, 61))
        self.titleLbl.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.titleLbl.setStyleSheet("background-color: rgb(118,255,163) ;\n"
"font-size: 32px;\n"
"font: italic bold;\n"
"color: rgb(65,183,60);\n"
"padding-left: 15px;\n"
"padding-right: 15px;\n"
"border-radius: 25px")
        self.titleLbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLbl.setObjectName("titleLbl")
        self.backBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.backBtn.setGeometry(QtCore.QRect(120, 510, 121, 51))
        self.backBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.backBtn.setAutoFillBackground(False)
        self.backBtn.setStyleSheet("background-color: rgb(65,183,60);\n"
"font: italic bold;\n"
"color: rgb(118,255,163);\n"
"font-size: 20px;\n"
"border-radius: 15px;\n"
"")
        self.backBtn.setAutoDefault(True)
        self.backBtn.setDefault(True)
        self.backBtn.setObjectName("backBtn")
        self.exitBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exitBtn.setGeometry(QtCore.QRect(460, 510, 121, 51))
        self.exitBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.exitBtn.setStyleSheet("background-color: rgb(65, 183, 60);\n"
"font: italic bold;\n"
"color: rgb(118,255,163);\n"
"font-size: 20px;\n"
"border-radius: 15px;\n"
"")
        self.exitBtn.setObjectName("exitBtn")
        displayWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=displayWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 680, 21))
        self.menubar.setObjectName("menubar")
        displayWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=displayWindow)
        self.statusbar.setObjectName("statusbar")
        displayWindow.setStatusBar(self.statusbar)

        self.retranslateUi(displayWindow)
        QtCore.QMetaObject.connectSlotsByName(displayWindow)

    def retranslateUi(self, displayWindow):
        _translate = QtCore.QCoreApplication.translate
        displayWindow.setWindowTitle(_translate("displayWindow", "MainWindow"))
        self.primaryLbl.setText(_translate("displayWindow", "Primary Income"))
        self.sideLbl.setText(_translate("displayWindow", "Side Income"))
        self.totalLbl.setText(_translate("displayWindow", "Total Income"))
        self.needsLbl.setText(_translate("displayWindow", "Needs"))
        self.wantsLbl.setText(_translate("displayWindow", "Wants"))
        self.saveLbl.setText(_translate("displayWindow", "Save"))
        self.label.setText(_translate("displayWindow", "Made By: Jonathan Cosby"))
        self.titleLbl.setText(_translate("displayWindow", "BudgetApp"))
        self.backBtn.setText(_translate("displayWindow", "Back"))
        self.exitBtn.setText(_translate("displayWindow", "Exit"))

        self.backBtn.clicked.connect(lambda:self.back(displayWindow))
        self.exitBtn.clicked.connect(self.exit)

    def exit(self):
        sys.exit()

    def back(self, displayWindow):
        displayWindow.hide()
