# Form implementation generated from reading ui file '/Users/benjicosby/Desktop/improveBudgetApp/invalidUserWindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_invalidUserWindow(object):
    def setupUi(self, invalidUserWindow):
        invalidUserWindow.setObjectName("invalidUserWindow")
        invalidUserWindow.resize(482, 187)
        self.centralwidget = QtWidgets.QWidget(parent=invalidUserWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 20, 341, 101))
        self.label.setStyleSheet("font-size: 25px;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        invalidUserWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=invalidUserWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 482, 21))
        self.menubar.setObjectName("menubar")
        invalidUserWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=invalidUserWindow)
        self.statusbar.setObjectName("statusbar")
        invalidUserWindow.setStatusBar(self.statusbar)

        self.retranslateUi(invalidUserWindow)
        QtCore.QMetaObject.connectSlotsByName(invalidUserWindow)

    def retranslateUi(self, invalidUserWindow):
        _translate = QtCore.QCoreApplication.translate
        invalidUserWindow.setWindowTitle(_translate("invalidUserWindow", "MainWindow"))
        self.label.setText(_translate("invalidUserWindow", "Invalid Username or Password"))
