# Form implementation generated from reading ui file '/Users/benjicosby/Desktop/improveBudgetApp/invalidWindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_invalidWindow(object):
    def setupUi(self, invalidWindow):
        invalidWindow.setObjectName("invalidWindow")
        invalidWindow.resize(400, 200)
        invalidWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=invalidWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 50, 111, 31))
        self.label.setMaximumSize(QtCore.QSize(351, 161))
        self.label.setStyleSheet("color: rgb(255,255,255);\n"
"font-size: 20px;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        invalidWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=invalidWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        invalidWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=invalidWindow)
        self.statusbar.setObjectName("statusbar")
        invalidWindow.setStatusBar(self.statusbar)

        self.retranslateUi(invalidWindow)
        QtCore.QMetaObject.connectSlotsByName(invalidWindow)

    def retranslateUi(self, invalidWindow):
        _translate = QtCore.QCoreApplication.translate
        invalidWindow.setWindowTitle(_translate("invalidWindow", "MainWindow"))
        self.label.setText(_translate("invalidWindow", "Invalid Entry"))
